/**全局*/
export const SAVE_LOCATION = 'SAVE_LOCATION';
export const SAVE_EXTEND = 'SAVE_EXTEND';
export const SAVE_CITY = 'SAVE_CITY';
/**抢购*/
export const GET_GOODS = 'GET_GOODS';
export const GET_CITY='GET_CITY';
export const GOODS_INFO = 'GOODS_INFO';
export const GOODS_DETAIL_INFO='GOODS_DETAIL_INFO';
/**附近*/


/**个人*/
export const USER_INFO = 'USER_INFO';
export const BILL_LIST = 'BILL_LIST';
export const AWARD_ACCEPT_LIST = 'AWARD_ACCEPT_LIST';
export const AWARD_WAIT_LIST = 'AWARD_WAIT_LIST';
export const TEAM_LIST = 'TEAM_LIST';
export const CLIENT_LIST = 'CLIENT_LIST';
export const STORE_INVITE_INFO = 'STORE_INVITE_INFO';
export const JSSDK_CONFIG_INFO = 'JSSDK_CONFIG_INFO';

/**公共*/
export const FETCH_INFO_DATA_SUCCESS='FETCH_INFO_DATA_SUCCESS';
export const FETCH_INFO_DATA_FAIL='FETCH_INFO_DATA_FAIL';
export const FETCH_INFO_DATA_REQUEST='FETCH_INFO_DATA_REQUEST';
export const FETCH_LIST_DATA_FAIL='FETCH_LIST_DATA_FAIL';
export const FETCH_LIST_DATA_REQUEST='FETCH_LIST_DATA_REQUEST';
export const FETCH_LIST_DATA_SUCCESS='FETCH_LIST_DATA_SUCCESS';
export const CLEAR_LIST_DATA='CLEAR_LIST_DATA';