
/**抢购*/
export const GET_GOODS = 'GET_GOODS';
export const GET_CITY='GET_CITY';
/**附近*/
export const GOODS_LIST = 'GOODS_LIST';

/**个人*/
export const USER_INFO = 'USER_INFO';
export const BILL_LIST = 'BILL_LIST';
/**公共*/
export const FETCH_INFO_DATA_SUCCESS='FETCH_INFO_DATA_SUCCESS';
export const FETCH_INFO_DATA_FAIL='FETCH_INFO_DATA_FAIL';
export const FETCH_INFO_DATA_REQUEST='FETCH_INFO_DATA_REQUEST';
export const FETCH_LIST_DATA_FAIL='FETCH_LIST_DATA_FAIL';
export const FETCH_LIST_DATA_REQUEST='FETCH_LIST_DATA_REQUEST';
export const FETCH_LIST_DATA_SUCCESS='FETCH_LIST_DATA_SUCCESS';
export const CLEAR_LIST_DATA='CLEAR_LIST_DATA';