
/**抢购*/
export const GOOD_LIST = 'GOOD_LIST';

/**个人*/
export const USER_INFO = 'USER_INFO';

/**公共*/
export const FETCH_INFO_DATA_SUCCESS='FETCH_INFO_DATA_SUCCESS';
export const FETCH_INFO_DATA_FAIL='FETCH_INFO_DATA_FAIL';
export const FETCH_INFO_DATA_REQUEST='FETCH_INFO_DATA_REQUEST';
export const FETCH_LIST_DATA_FAIL='FETCH_LIST_DATA_FAIL';
export const FETCH_LIST_DATA_REQUEST='FETCH_LIST_DATA_REQUEST';
export const FETCH_LIST_DATA_SUCCESS='FETCH_LIST_DATA_SUCCESS';